package ec.edu.ups.appdis.g1.lojaandressrijee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-05T12:47:59.828-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "AceptarFacturaService", 
                  wsdlLocation = "file:/C:/Users/aloja/AppData/Local/Temp/tempdir1445273025647767299.tmp/AceptarFactura_1.wsdl",
                  targetNamespace = "http://LojaAndresSRIJEE.g1.appdis.ups.edu.ec/") 
public class AceptarFacturaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://LojaAndresSRIJEE.g1.appdis.ups.edu.ec/", "AceptarFacturaService");
    public final static QName AceptarFacturaPort = new QName("http://LojaAndresSRIJEE.g1.appdis.ups.edu.ec/", "AceptarFacturaPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/aloja/AppData/Local/Temp/tempdir1445273025647767299.tmp/AceptarFactura_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AceptarFacturaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/aloja/AppData/Local/Temp/tempdir1445273025647767299.tmp/AceptarFactura_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AceptarFacturaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AceptarFacturaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AceptarFacturaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AceptarFacturaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AceptarFacturaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AceptarFacturaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AceptarFactura
     */
    @WebEndpoint(name = "AceptarFacturaPort")
    public AceptarFactura getAceptarFacturaPort() {
        return super.getPort(AceptarFacturaPort, AceptarFactura.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AceptarFactura
     */
    @WebEndpoint(name = "AceptarFacturaPort")
    public AceptarFactura getAceptarFacturaPort(WebServiceFeature... features) {
        return super.getPort(AceptarFacturaPort, AceptarFactura.class, features);
    }

}
