
package ec.edu.ups.appdis.g1.lojaandressrijee;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-05T12:47:59.794-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class AceptarFactura_AceptarFacturaPort_Client {

    private static final QName SERVICE_NAME = new QName("http://LojaAndresSRIJEE.g1.appdis.ups.edu.ec/", "AceptarFacturaService");

    private AceptarFactura_AceptarFacturaPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AceptarFacturaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AceptarFacturaService ss = new AceptarFacturaService(wsdlURL, SERVICE_NAME);
        AceptarFactura port = ss.getAceptarFacturaPort();  
        
        {
        System.out.println("Invoking facturalo...");
        ec.edu.ups.appdis.g1.lojaandressrijee.Datos _facturalo_arg0 = null;
        java.lang.String _facturalo__return = port.facturalo(_facturalo_arg0);
        System.out.println("facturalo.result=" + _facturalo__return);


        }

        System.exit(0);
    }

}
