package ec.edu.ups.appdis.g1.operadora;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-05T10:14:04.178-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "AceptarRecargaService", 
                  wsdlLocation = "file:/C:/Users/aloja/AppData/Local/Temp/tempdir867513237524928001.tmp/AceptarRecarga_1.wsdl",
                  targetNamespace = "http://operadora.g1.appdis.ups.edu.ec/") 
public class AceptarRecargaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://operadora.g1.appdis.ups.edu.ec/", "AceptarRecargaService");
    public final static QName AceptarRecargaPort = new QName("http://operadora.g1.appdis.ups.edu.ec/", "AceptarRecargaPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/aloja/AppData/Local/Temp/tempdir867513237524928001.tmp/AceptarRecarga_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AceptarRecargaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/aloja/AppData/Local/Temp/tempdir867513237524928001.tmp/AceptarRecarga_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AceptarRecargaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AceptarRecargaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AceptarRecargaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AceptarRecargaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AceptarRecargaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AceptarRecargaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AceptarRecarga
     */
    @WebEndpoint(name = "AceptarRecargaPort")
    public AceptarRecarga getAceptarRecargaPort() {
        return super.getPort(AceptarRecargaPort, AceptarRecarga.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AceptarRecarga
     */
    @WebEndpoint(name = "AceptarRecargaPort")
    public AceptarRecarga getAceptarRecargaPort(WebServiceFeature... features) {
        return super.getPort(AceptarRecargaPort, AceptarRecarga.class, features);
    }

}
