package ec.edu.ups.appdis.g1.operadora;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-05T10:14:04.174-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://operadora.g1.appdis.ups.edu.ec/", name = "AceptarRecarga")
@XmlSeeAlso({ObjectFactory.class})
public interface AceptarRecarga {

    @WebMethod
    @RequestWrapper(localName = "deposito", targetNamespace = "http://operadora.g1.appdis.ups.edu.ec/", className = "ec.edu.ups.appdis.g1.operadora.Deposito")
    @ResponseWrapper(localName = "depositoResponse", targetNamespace = "http://operadora.g1.appdis.ups.edu.ec/", className = "ec.edu.ups.appdis.g1.operadora.DepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int deposito();
}
